name: envs
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5
  - async-timeout=4.0.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cryptography=37.0.1
  - deprecated=1.2.13
  - idna=3.4
  - importlib-metadata=4.11.4
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.39.4
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.5
  - packaging=21.3
  - pip=22.3
  - pycparser=2.21
  - pydantic=1.10.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.6
  - python-dotenv=0.21.0
  - python_abi=3.10
  - readline=8.1.2
  - redis-py=4.3.4
  - requests=2.28.1
  - setuptools=65.5.0
  - six=1.16.0
  - spotipy=2.20.0
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022e
  - urllib3=1.26.11
  - wheel=0.37.1
  - wrapt=1.14.1
  - xz=5.2.6
  - zipp=3.9.0