[tool.poetry]
name = "skiptify"
version = "0.1.0"
description = ""
authors = ["Basel Hack Skiptify team"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
